# Build Settings
encoding: utf-8
include: ['_pages']
paginate_path: '/page:num/'
paginate: 5
permalink: '/:categories/:title/'
strict_front_matter: true
timezone: Europe/Kiev

# Plugin Settings
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-twitter-plugin

# Default Settings
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      read_time: true
      related: true
      share: true
      show_date: true
      toc_sticky: true
      toc: true
  - scope:
      path: ''
      type: pages
    values:
      layout: single
      author_profile: true

# Site Settings
description: Personal technical blog of some guy from Kyiv, Ukraine. I write, mostly, about Node.js, TypeScript and Developer Experience.
locale: en
logo: assets/images/logo/masthead-logo.png
masthead_title: Eugene Obrezkov
minimal_mistakes_skin: dirt
name: Eugene Obrezkov
remote_theme: mmistakes/minimal-mistakes
repository: ghaiklor/blog.ghaiklor.com
search: true
subtitle: 'Personal technical blog of some guy from Kyiv, Ukraine'
teaser: assets/images/placeholder/500x300.png
title_separator: ⸱
title: Blog ⸱ Eugene Obrezkov

# Comments Settings
comments:
  provider: utterances
  utterances:
    theme: github-light
    issue_term: pathname

# SEO Settings
twitter:
  username: ghaiklor
facebook:
  username: ghaiklor
og_image: assets/images/logo/logo.png
social:
  type: Person
  name: Eugene Obrezkov
  links:
    - 'https://www.facebook.com/ghaiklor'
    - 'https://twitter.com/ghaiklor'
    - 'https://github.com/ghaiklor'

# Analytics Settings
analytics:
  provider: google-gtag
  google:
    tracking_id: G-2JFB8L74FD
    anonymize_ip: false

# Author Settings
author:
  name: Eugene Obrezkov
  avatar: assets/images/avatar/ghaiklor.jpg
  bio: Software Engineer · Node.js · Rust · D2D (programming languages, compilers, developer tools)
  location: 'Kyiv, Ukraine'
  links:
    - label: Email
      icon: fas fa-fw fa-envelope-square
      url: 'mailto:ghaiklor@gmail.com'
    - label: Website
      icon: fas fa-fw fa-link
      url: 'https://ghaiklor.com'
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: 'https://twitter.com/ghaiklor'
    - label: Facebook
      icon: fab fa-fw fa-facebook-square
      url: 'https://facebook.com/ghaiklor'
    - label: GitHub
      icon: fab fa-fw fa-github
      url: 'https://github.com/ghaiklor'
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: 'https://instagram.com/ghaiklor'

# Footer Settings
footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: 'https://twitter.com/ghaiklor'
    - label: Facebook
      icon: fab fa-fw fa-facebook-square
      url: 'https://facebook.com/ghaiklor'
    - label: GitHub
      icon: fab fa-fw fa-github
      url: 'https://github.com/ghaiklor'
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: 'https://instagram.com/ghaiklor'

# Archive Settings
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
